assets:
    - id: kyve_mainnet_native
      decimals: 6
      blockchain:
        name: "Kyve Mainnet"
        rpc_url: "https://api.kyve.network/"
      module: "cosmos_native"
      name: KYVE
      extra_parameters:
        validator:
          window_block_missed_threshold: 100
      accounts:
        - address: "kyve14tq3f6tgcwfmrhjcnasq5a3rqm2e636wj5ptmt"
          name: "Coinpri Validator"
          is_validator: true
          extra_args: bar
    # - id: avail_mainnet_native
    #   decimals: 18
    #   blockchain:
    #     name: "Avail Mainnet"
    #     rpc_url: "https://mainnet-rpc.avail.so/rpc"
    #   module: "avail"
    #   name: AVL
    #   accounts:
    #     - address: "5Fv2hc7PispHEDVVXptkuC2YkmwutYhSvn1yMdWKcVabii1z"
    #       name: "Exaion-Coinpri Validator"
    #     - address: "5EtBK27SeMG1iRE9v91BU4KX8zpsT5Q61rpxdUggMbFffjtq"
    #       name: "Coinpri Nomination Pool #20"
    #     - address: "5G1Y8yv4SgYa6n8H9DnC8bH6X4QwHsRL295WVZTCR8ViatS3"
    #       name: "DeadPool Nomination Pool #27"