{
 "title": "Web3 Prometheus Exporter",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "asset",
    "label": "Asset",
    "query": {
     "query": "label_values({__name__=~\"^web3_prometheus_exporter_.+_account_balance$\"},asset_name)"
    }
   },
   {
    "name": "account",
    "label": "Account",
    "query": {
     "query": "label_values({__name__=~\"^web3_prometheus_exporter_.+_account_balance$\", asset_name=\"$asset\"},account)"
    }
   },
   {
    "name": "decimals",
    "label": "Decimals",
    "query": {
     "query": "query_result(sum by (decimals) (rate({__name__=~\"^web3_prometheus_exporter_.+_account_balance$\", asset_name=\"$asset\"}[1m])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Asset accounts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(account) ({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "24-hours balance change accross all accounts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"}[24h])) * 60 * 60 * 24 / 10 ^ $decimals)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Accounts Total Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"} / 10^$decimals)",
     "legendFormat": "{{asset_name}}"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (blockchain_name) ({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accounts Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (account, address) ({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"} / 10^$decimals)",
     "legendFormat": "Total account balance"
    },
    {
     "expr": "sum by (account, address) ((rate({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"}[24h])) * 60 * 60 * 24 / 10 ^ $decimals)",
     "legendFormat": "24h change"
    }
   ]
  },
  {
   "title": "Blockchain RPC URL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rpc_url) ({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"})",
     "legendFormat": "{{rpc_url}}"
    }
   ]
  },
  { "title": "Accounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$account $asset balance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "repeat": "account",
   "targets": [
    {
     "expr": "sum by (balance_name) ({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\", account=\"$account\"} / 10^$decimals)",
     "legendFormat": "{{asset_name}}: {{balance_name}}"
    }
   ]
  },
  {
   "title": "$account 24-hours rate of change",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "repeat": "account",
   "targets": [
    {
     "expr": "(rate({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\", account=\"$account\"}[24h])) * 60 * 60 * 24 / 10 ^ $decimals",
     "legendFormat": "{{asset_name}}: {{balance_name}}"
    }
   ]
  }
 ]
}