{
 "title": "Validator statuses",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "asset",
    "label": "Asset",
    "query": {
     "query": "label_values(web3_prometheus_exporter_validator_status,asset_name)"
    }
   },
   {
    "name": "account",
    "label": "Account",
    "query": {
     "query": "label_values(web3_prometheus_exporter_validator_status{asset_name=\"$asset\"},account)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Asset Validators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (web3_prometheus_exporter_validator_status{asset_name=\"$asset\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Validators not \"up\"",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (web3_prometheus_exporter_validator_status{asset_name=\"$asset\", status!=\"up\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Validator statuses",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (web3_prometheus_exporter_validator_status{asset_name=\"$asset\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (blockchain_name) ({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blockchain RPC URL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rpc_url) ({asset_name=\"$asset\", __name__=~\"^web3_prometheus_exporter_.+_account_balance$\"})",
     "legendFormat": "{{rpc_url}}"
    }
   ]
  },
  {
   "title": "Validator statuses details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (account, address, asset_name, blockchain_name, status, rpc_url) (web3_prometheus_exporter_validator_status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}