import chip
import exporter/prometheus
import gleam/dict.{type Dict}
import gleam/erlang/process.{type Pid, type Subject}
import gleam/list
import gleam/option.{type Option}
import gleam/otp/actor
import gleam/otp/erlang_supervisor as erlsup
import gleam/yielder
import snag

/// Generalized message type for blockchain actors.
pub type Message {
  QueryBalance(
    asset_id: String,
    account_id: String,
    caller_subject: Subject(snag.Result(Int)),
  )
  GetAssets(caller_subject: Subject(List(Asset)))
  GetAccounts(
    asset_id: String,
    caller_subject: Subject(snag.Result(List(Account))),
  )
  // GetExtraLabels(caller_subject)
}

/// Generalized Asset type returned by the `GetAssets`
/// message type
pub type Asset {
  Asset(
    id: String,
    kind: String,
    details: Dict(String, String),
    timeout: Option(Int),
    interval: Option(Int),
  )
}

/// Generalized Account type returned by the `GetAccounts`
/// message type
pub type Account {
  Account(
    id: String,
    address: String,
    details: Dict(String, String),
    timeout: Option(Int),
    interval: Option(Int),
  )
}

// `interval` and `timeout` are optional configs either for
// the blockchain, asset, or account. If none is provided, these
// values are used (in ms)
const default_timeout = 10_000

const default_interval = 15_000

/// Takes a blockchain actor (like the one generated by `evm/blockchain.to_actor`)
/// turns it into a supervisor `otp/erlang_supervisor.ChildBuilder`,
/// then starts a bunch of "timer" child processes.
/// The "timer" processes are infinitely-looping `erlang/process`es, not actors,
/// and simply query the balance of each configured asset-account pair
/// at a given interval, with a given timeout.
pub fn actor_to_child_builder(
  blockchain_actor blockchain_actor: actor.Spec(Nil, Message),
  blockchain_id blockchain_id: String,
  prometheus_subject prometheus_subject: Subject(prometheus.Message),
  registry registry: chip.Registry(Message, String),
  blockchain_interval blockchain_interval: Option(Int),
  blockchain_timeout blockchain_timeout: Option(Int),
) -> erlsup.ChildBuilder {
  //
  // Building the starter function of the `ChildBuilder`.
  // It will be executed after the supervisor is started.
  // This starter function registers the new blockchain's subject to the chip subject registry,
  // creates a "timer" process for each asset-account pair, and starts those "timer" processes
  // with `erlang_supervisor.start_child`.
  let start_supervisor_child = fn(blockchain_supervisor) {
    let assert Ok(evm_process_subject) = actor.start_spec(blockchain_actor)

    chip.register(registry, blockchain_id, evm_process_subject)

    let assets = process.call(evm_process_subject, GetAssets, 100)
    use asset <- list.each(assets)
    let assert Ok(accounts) =
      process.call(evm_process_subject, GetAccounts(asset.id, _), 100)
    use account <- list.each(accounts)

    let interval =
      option.unwrap(
        account.interval,
        option.unwrap(
          asset.interval,
          option.unwrap(blockchain_interval, default_interval),
        ),
      )
    let timeout =
      option.unwrap(
        account.timeout,
        option.unwrap(
          asset.timeout,
          option.unwrap(blockchain_timeout, default_timeout),
        ),
      )

    let timer_child =
      erlsup.worker_child(
        asset.id <> "-" <> account.id,
        make_timer_loop(
          evm_process_subject,
          prometheus_subject,
          asset.id,
          asset.details,
          account.id,
          account.address,
          account.details,
          timeout,
          interval,
        ),
      )
      |> erlsup.timeout(timeout + interval + 1000)
    let assert Ok(_) =
      blockchain_supervisor
      |> erlsup.start_child(timer_child)
    // Stagger timer processes starts to spread out their triggers
    process.sleep(420)

    Nil
  }

  erlsup.new(erlsup.OneForOne)
  |> erlsup.supervisor_child(blockchain_id, start_supervisor_child)
}

/// `starter` function for the "timer" child processes.
/// Returns a function that loops infinitely at an interval,
/// querying the balance for the configured asset and account to the blockchain subject,
/// then forwards the result to the prometheus subject on balance changes.
fn make_timer_loop(
  blockchain_subject: Subject(Message),
  prometheus_subject: Subject(prometheus.Message),
  asset_id: String,
  asset_details: Dict(String, String),
  account_id: String,
  account_address: String,
  account_details: Dict(String, String),
  timeout_s: Int,
  interval_s: Int,
) -> fn() -> Result(Pid, Nil) {
  // We have to wrap `process.start` in an `Ok` because it returns a raw Pid,
  // and we need a `Result(Pid, Nil)
  let interval_ms = interval_s * 1000
  let timeout_ms = timeout_s * 1000
  fn() {
    Ok(process.start(
      fn() {
        let subject = process.new_subject()
        use last_balance, _ <- yielder.fold(yielder.repeat(Nil), 0)

        // Using a `process.Timer` to send messages at regular intervals
        // The alternative would've been to use `process.sleep`, but
        // that's not recommended (not sure, lol)
        let _timer =
          process.send_after(
            blockchain_subject,
            interval_ms,
            QueryBalance(asset_id, account_id, subject),
          )

        // Waiting for the response from the timer.
        // Asserting the result because if the blockchain process isn't responding,
        // this timer process is dangling and useless and should die.
        let assert Ok(balance_result) =
          process.receive(subject, interval_ms + timeout_ms)

        // an error from `balance_result` means the blockchain process works,
        // but failed to build the new balance, for instance
        // from an RPC connectivity issue.
        // In that case, we don't wanna crash, just keep the previous result.
        case balance_result {
          Error(_) -> last_balance
          // Only contact the prometheus subject if the balance has changed.
          Ok(new_balance) if new_balance == last_balance -> last_balance
          Ok(new_balance) -> {
            let labels =
              dict.from_list([
                #("asset", asset_id),
                #("account", account_id),
                #("address", account_address),
              ])
              |> dict.combine(asset_details, fn(_, _) {
                panic as "found same label keys in asset details"
              })
              |> dict.combine(account_details, fn(_, _) {
                panic as "found same label keys in account details"
              })
            process.send(
              prometheus_subject,
              prometheus.UpdateBalance(new_balance, labels),
            )
            new_balance
          }
        }
      },
      False,
    ))
  }
}
